apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cxr-frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/sessionAffinity: "true"
    spec:
      timeoutSeconds: 3600
      containerConcurrency: 80
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/cxr/frontend:latest
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: BACKEND_URL
              value: https://cxr-backend-HASH-REGION.run.app
          ports:
            - containerPort: 8501
